#!/bin/bash
# Cleanup script to remove temporary files before arXiv submission

echo "Cleaning up temporary files..."

cd "$(dirname "$0")"

# Remove LaTeX temporary files
rm -f *.aux *.bbl *.blg *.log *.out *.synctex.gz *.toc *.lof *.lot *.fls *.fdb_latexmk

# Remove PDF (will be regenerated by arXiv)
rm -f *.pdf

echo "✓ Cleanup complete!"
echo ""
echo "Files remaining:"
ls -1
